sudo: required

# Go for Kubernetes in Docker
language: go
go:
  - '1.11.x'

dist: xenial

services:
  - docker

# Default Travis version of compose does not suffice
env:
  - DOCKER_COMPOSE_VERSION=1.22.0
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
 
jobs:
  include:
    - stage: bootstrap-deploy-test
      script:
        - make bootstrap           # Install deps
        - make deploy              # Deploy infrastructure and services
        - make test                # Test ioFog services
      after_success:
        - TAG=rel make push-imgs   # Push release packages
      after_script:
        - make rm-gcp              # Teardown GCP clusters
