sudo: required

language: python
python:
  - "2.7"
cache: pip
install:
  - pip install -r requirements.txt

dist: xenial

services:
  - docker
 
jobs:
  include:
    - stage: bootstrap-deploy-test
      script:
      - |
        printenv GCP_SVC_ACC > plugins/gcp/creds/svcacc.json &&
        python cli.py up gcp --bootstrap=true &&
        python cli.py up iofog --bootstrap=true &&
        python cli.py up weather &&
        python cli.py test weather
      after_script:
        - python cli.py down gcp
