apiVersion: apps/v1
kind: Deployment
metadata:
  name: iofog-controller
  labels:
    app: iofog-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iofog-controller
  template:
    metadata:
      labels:
        app: iofog-controller
    spec:
      containers:
      - name: iofog-controller
        image: iofog/controller:dev